version: "3"
services:
  node-app:
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    restart: always
    volumes:
      - dbmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
  redis:
    image: redis
volumes:
  dbmysql:
